stages:
  - compose

stage_compose:
  stage: compose
  image: docker:stable
  when: manual
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t test:latest .
    - docker tag test:latest $CI_REGISTRY_USER/test:latest
    - docker push $CI_REGISTRY_USER/test:latest
